version: '3'

services:
  my_openresty:
    image: openresty/openresty:buster-fat
    network_mode: host
    volumes:
      - ./:/var/www
      - ./dockerfile/vc-nginx-site.conf:/etc/nginx/conf.d/default.conf
      - ./dockerfile/website-ssl-cert:/etc/nginx/ssl-cert
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5g"

  my_php:
    hostname: php
    network_mode: host
    privileged: true
    build:
      context: ./dockerfile
      dockerfile: ./php.Dockerfile
    volumes:
      - ./dockerfile/vc-php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./dockerfile/vc-zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./dockerfile/vc-php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
      - ./dockerfile/supervisor.conf.d:/etc/supervisor/conf.d
      - ./docker-data/crontabs:/var/spool/cron/crontabs
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5g"

  my_mysql:
      hostname: mysql
      container_name: my_mysql
      image: mysql:8.0
      ports:
          - 3306:3306
      volumes:
          - /etc/localtime:/etc/localtime
          - ./docker-data/mysql/var/lib/mysql:/var/lib/mysql
          - ./dockerfile/my.cnf:/etc/my.cnf
      command:
          --max_connections=1000
          --character-set-server=utf8mb4
          --collation-server=utf8mb4_general_ci
          --default-authentication-plugin=mysql_native_password
          --default-time-zone=+8:00
      environment:
          - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      privileged: true
      restart: always

#  redis:
#      container_name: redis
#      image: redis:6.0.9
#      ports:
#          - 6379:6379
#      volumes:
#          - ./dockerfile/redis.conf:/etc/redis.conf
#          - ./docker-data/redis:/data
#          - /etc/localtime:/etc/localtime
#      command: redis-server /etc/redis.conf
#      privileged: true
#      restart: always

#  rabbitmq:
#      hostname: rabbitmq
#      container_name: rabbitmq
#      image: rabbitmq:3.7-rc-management
#      network_mode: host
#      environment:
#          - "RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}"
#          - "RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}"
#      volumes:
#          - ./docker-data/rabbitmq/lib/rabbitmq:/var/lib/rabbitmq
#          - ./docker-data/rabbitmq/log:/var/log/rabbitmq
#          - ./dockerfile/rabbitmq-ssl-cert:/etc/rabbitmq/ssl-cert
#      restart: always
#      logging:
#          driver: "json-file"
#          options:
#              max-size: "5g"

#  maxwell:
#      hostname: maxwell
#      network_mode: host
#      build:
#          context: ./dockerfile
#          dockerfile: ./maxwell.Dockerfile
#      environment:
#          - "MYSQL_USERNAME=root"
#          - "MYSQL_PASSWORD=${DB_ROOT_PASSWORD}"
#          - "MYSQL_HOST=localhost"
#          - "MAXWELL_PRODUCER=rabbitmq"
#      volumes:
#          - ./dockerfile/maxwell.config.properties:/usr/local/maxwell/config.properties
#      restart: always
#      depends_on:
#          - mysql
#          - rabbitmq
#      logging:
#          driver: "json-file"
#          options:
#              max-size: "5g"



