version: '3'

services:
  openresty:
    image: openresty/openresty:buster-fat
    network_mode: host
    volumes:
      - ./:/var/www
      - ./dockerfile/vc-nginx-site.conf:/etc/nginx/conf.d/default.conf
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5g"

  php:
    hostname: php
    network_mode: host
    privileged: true
    build:
      context: ./dockerfile
      dockerfile: ./php.Dockerfile
    volumes:
      - ./dockerfile/vc-php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./dockerfile/vc-php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
      - ./dockerfile/supervisor.conf.d:/etc/supervisor/conf.d
      - ./docker-data/crontabs:/var/spool/cron/crontabs
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5g"

  mysql:
      container_name: mysql
      image: mysql:8.0
      ports:
          - 127.0.0.1:3306:3306
      volumes:
          - /etc/localtime:/etc/localtime
          - /data/mysql_data:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
          - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      privileged: true
      restart: always

  redis:
      container_name: redis
      image: redis:6.0.9
      ports:
          - 127.0.0.1:6379:6379
      volumes:
          - /data/redis:/data
          - /etc/localtime:/etc/localtime
      command: redis-server requirepass ${REDIS_PASSWORD} --appendonly yes
      privileged: true
      restart: always

  maxwell:
      hostname: maxwell
      network_mode: host
      build:
          context: ./dockerfile
          dockerfile: ./maxwell.Dockerfile
      environment:
          - "MYSQL_USERNAME=root"
          - "MYSQL_PASSWORD=${DB_ROOT_PASSWORD}"
          - "MYSQL_HOST=mysql"
          - "MAXWELL_PRODUCER=rabbitmq"
      volumes:
          - ./dockerfile/maxwell.config.properties:/usr/local/maxwell/config.properties
      restart: always
      logging:
          driver: "json-file"
          options:
              max-size: "5g"

  rabbitmq:
      hostname: rabbitmq
      container_name: rabbitmq
      image: rabbitmq:3.7-rc-management
      network_mode: host
      environment:
          - "RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}"
          - "RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}"
      volumes:
          - ./docker-data/rabbitmq/lib/rabbitmq:/var/lib/rabbitmq
          - ./docker-data/rabbitmq/log:/var/log/rabbitmq
      restart: always
      logging:
          driver: "json-file"
          options:
              max-size: "5g"



